FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api-simple.py .

EXPOSE 3002

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:3002", "--access-logfile", "-", "--error-logfile", "-", "api-simple:app"]
